server:
  port: 3344
spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com #自己的仓库名字
          ###搜索目录
          search-paths:
            - springcloud-config
       #读取分支
      label: master

#rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#注册微服务
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

##rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

