server:
  port: 8002

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.liben.springcloud.entities


spring:
  application:
    name: cloud-payment-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding-utr-8&useSSL=false
      username: root
      password: 12345678

eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
    #入驻地址
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8002 #对外暴露服务名称
    prefer-ip-address: true #访问路径可以显示IP
    #Eureka客户端向服务端发送心跳的时间间隔 默认30秒
    #lease-expiration-duration-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后的等待时间上限，默认90秒 ，超时将剔除服务
    #lease-renewal-interval-in-seconds: 2



